### ISSUE TITLE
[feature] Anthropic / Claude2 Support

### ISSUE THREAD

**Issue by robertmeta** [ahyatt/llm#22]
Anthropic is a close peer to OpenAI in text generation terms, and has a larger available context window that is compatible with its newest model, at 200k tokens. The API feels very similar in terms of tokens and the conversation back and forth.

I personally often favor the output of Anthropic over both Gemini and GPT-4.

**Comment by ahyatt** [comment]
I think the Claude 2 API is a [closed beta](https://support.anthropic.com/en/articles/8114521-how-can-i-access-the-claude-api), so most people (including me) cannot use it.  It's good in theory, though, since Claude 2 is supposed to be good, as you point out.  Let me know, though, if I'm misunderstanding the API access story, though.

**Comment by ahyatt** [comment]
Good news, I've implemented Claude (which has opened up its API) and released it in the latest llm release!  Please let me know if you find any issues with it.

**Comment by robertmeta** [comment]
Awesome, look forward to trying it with Ellama.
